// app/layout.jsx
import "./globals.css";
import localFont from "next/font/local";

/** @type {import('next').Metadata} */
export const metadata = {
  title: "Tickets NEOMOMENT",
  description: "Generated by create next app",
};

// Sans — Geist (TTF files)
const geistSans = localFont({
  src: [
    { path: "./fonts/Geist-Light.ttf",   weight: "300", style: "normal" },
    { path: "./fonts/Geist-Regular.ttf", weight: "400", style: "normal" },
    { path: "./fonts/Geist-Medium.ttf",  weight: "500", style: "normal" },
    { path: "./fonts/Geist-Bold.ttf",    weight: "700", style: "normal" },
    { path: "./fonts/Geist-Black.ttf",   weight: "900", style: "normal" },
  ],
  variable: "--font-geist-sans",
  display: "swap",
  fallback: ["ui-sans-serif", "system-ui", "Helvetica", "Arial"],
});

// Mono — Geist Mono (TTF files)
const geistMono = localFont({
  src: [
    { path: "./fonts/Geist-Regular.ttf", weight: "400", style: "normal" },
    { path: "./fonts/Geist-Bold.ttf",    weight: "700", style: "normal" },
    { path: "./fonts/Geist-Black.ttf",   weight: "900", style: "normal" },
  ],
  variable: "--font-geist-mono",
  display: "swap",
  fallback: ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
